version: '3.7'

services:
  db:
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=141928
      - POSTGRES_DB=demo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./grsmu_diplom:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost
      - DB_NAME=demo
      - DB_USER=postgres
      - DB_PASSWORD=141928
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  db_data: